services:

  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "TZ=Europe/Madrid"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 0 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_WATCH_RUNONSTARTUP=true"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"

      - "DIUN_NOTIF_GOTIFY_ENDPOINT=http://localhost:8008"
      - "DIUN_NOTIF_GOTIFY_TOKEN=xxxxxxxxxxxx" # get your token from Gotify UI
      - "DIUN_NOTIF_GOTIFY_PRIORITY=1"
      - "DIUN_NOTIF_GOTIFY_TIMEOUT=10s" 
      
    labels:
      - "diun.enable=true"
  
